{% set name = "texify" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/texify-{{ version }}.tar.gz
  sha256: 4fed5946e4b334a4f59d948f7d8338dc31d609fefcab3e7661ee3195a9be4f20

build:
  entry_points:
    - texify = ocr_image:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - poetry-core
    - pip
  run:
    - python >=3.9,<4.0,!=3.9.7
    - transformers >=4.36.2,<5.0.0
    - pytorch >=2.1.2,<3.0.0
    - pydantic >=2.5.2,<3.0.0
    - pydantic-settings >=2.1.0,<3.0.0
    - pillow >=10.1.0,<11.0.0
    - numpy >=1.26.2,<2.0.0
    - pypdfium2 >=4.25.0,<5.0.0
    - python-dotenv >=1.0.0,<2.0.0
    - ftfy >=6.1.3,<7.0.0

test:
  imports:
    - texify
  commands:
    - pip check
    - texify --help
  requires:
    - pip

about:
  home: https://github.com/VikParuchuri/texify
  summary: OCR for latex images
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
